"""Make polygon_id nullable in areas

Revision ID: d30a1f049212
Revises: 
Create Date: 2025-11-02 18:45:50.663195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30a1f049212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('polygon_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('polygon_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
